function [psi, phi, gamma] = computeGammaSingleSinus(...
    crossCorrelationVectors, a, hankelMatrixIsAdded, dcIsIncluded)

    R = computeRowsOfToeplitzHankelMatrix(1, 1, ...
                                          crossCorrelationVectors, ...
                                          hankelMatrixIsAdded, ...
                                          dcIsIncluded);
    psi = 1./R(1, :);
    gamma = psi;
    phi = a.*gamma;
end
